import IconArrow from './IconArrow'
import IconBasket from './IconBasket'
import IconCategories from './IconCategories'
import IconClose from './IconClose'
import IconDashboard from './IconDasboard'
import IconEdit from './IconEdit'
import IconFAQ from './IconFAQ'
import IconLogout from './IconLogout'
import IconMenu from './IconMenu'
import IconNoImg from './IconNoImg'
import IconProducts from './IconProducts'
import IconRemove from './IconRemove'
import IconRemoved from './IconRemoved'
import IconReviews from './IconReviews'
import IconShop from './IconShop'

export { IconArrow, IconBasket, IconClose, IconRemove, IconNoImg, IconShop, IconDashboard, IconMenu, IconCategories, IconProducts, IconEdit, IconRemoved, IconReviews, IconFAQ, IconLogout }